---
- name: Template systemd service
  ansible.builtin.template:
    src: control.service.j2
    dest: "/etc/systemd/system/{{ service.name }}.service"
    owner: root
    group: root
    mode: "0644"
    force: true

- name: Start control
  ansible.builtin.systemd_service:
    name: "{{ service.name }}.service"
    state: restarted
    enabled: true
    masked: false
    daemon_reload: true

- name: Wait for control to be ready
  ansible.builtin.wait_for:
    host: "127.0.0.1"
    port: "{{ service.port }}"
    timeout: 300
    state: started
...
