---
- name: Ensure ngircd directories
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/ngircd/config"
    state: directory
    owner: "{{ ansible_user }}"
    mode: "0755"

- name: Ensure ngircd cert dir
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/ngircd/certs"
    state: directory
    owner: "{{ ansible_user }}"
    mode: "0700"

- name: Template compose file
  ansible.builtin.template:
    src: ngircd.compose.yaml.j2
    dest: "{{ ansible_facts['user_dir'] }}/ngircd/compose.yaml"
    owner: "{{ ansible_user }}"
    mode: "0600"
    force: true

- name: Copy ngircd conf
  ansible.builtin.copy:
    src: "ngircd.conf/{{ ansible_facts['hostname'] }}"
    dest: "{{ ansible_facts['user_dir'] }}/ngircd/config/ngircd.conf"
    owner: "{{ ansible_user }}"
    mode: "0600"
    force: true

- name: Generate DH params
  community.crypto.openssl_dhparam:
    path: "{{ ansible_facts['user_dir'] }}/ngircd/certs/dhparams.pem"
    size: 2048
    owner: "{{ ansible_user }}"
    mode: '0600'
...
