---
- name: Disable apt timers
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: stopped
    enabled: false
    masked: true
    daemon_reload: true
  loop:
    - "apt-daily-upgrade.timer"
    - "apt-daily.timer"
...
