---
- name: Copy robots txt
  ansible.builtin.copy:
    src: "robots.txt"
    dest: "/var/www/{{ robots_txt_domain }}/robots.txt"
    owner: www-data
    group: www-data
    mode: "0640"
    force: true
...
