---
- name: Ensure cert dirs
  ansible.builtin.file:
    path: "{{ item.dir }}"
    state: directory
    owner: "{{ ansible_user }}"
    mode: "0700"
  loop: "{{ selfsigned_certs }}"

- name: Generate private keys
  community.crypto.openssl_privatekey:
    path: "{{ item.dir }}/privkey.pem"
    type: RSA
    size: 4096
    state: present
    owner: "{{ ansible_user }}"
    mode: "0600"
    force: true
  loop: "{{ selfsigned_certs }}"

- name: Create CSRs
  community.crypto.openssl_csr:
    path: "{{ item.dir }}/cert.csr"
    privatekey_path: "{{ item.dir }}/privkey.pem"
    subject_alt_name: "{{ item.san }}"
    state: present
    owner: "{{ ansible_user }}"
    mode: "0600"
    force: true
  loop: "{{ selfsigned_certs }}"

- name: Generate selfsigned certs
  community.crypto.x509_certificate:
    path: "{{ item.dir }}/fullchain.pem"
    privatekey_path: "{{ item.dir }}/privkey.pem"
    csr_path: "{{ item.dir }}/cert.csr"
    provider: selfsigned
    selfsigned_not_after: "+825d"
    state: present
    owner: "{{ ansible_user }}"
    mode: "0600"
    force: true
  loop: "{{ selfsigned_certs }}"
...
