---
- name: Set up context as unprivileged user
  hosts: "{{ target_hosts | default('node1') }}"
  become: false
  gather_facts: true

- name: Install services
  hosts: "{{ target_hosts | default('node1') }}"
  become: true
  gather_facts: false
  vars:
    irc_domain: "irc.mesh"
    irc_network_password: ""

    thelounge_name: "thelounge-home"
    thelounge_port: "11001"

    ngircd_name: "ngircd-home"
    ngircd_tls_port: "11003"

  roles:
    - { role: ngircd_install, tags: ngircd_install }
    - { role: thelounge_install, tags: thelounge_install }
    - { role: thelounge_themes, tags: thelounge_themes }
...
