---
- name: Set up context as unprivileged user
  hosts: "{{ target_hosts | default('node2') }}"
  become: false
  gather_facts: true

- name: Configure network interfaces
  hosts: "{{ target_hosts | default('node2') }}"
  become: true
  gather_facts: false
  vars:
    systemd_networkd_apply_config: true
    systemd_networkd_enable_resolved: false
    systemd_networkd_symlink_resolv_conf: false

    systemd_networkd_netdev:
      "10-br-mesh":
        - NetDev:
            - Name: "br-mesh"
            - Kind: "bridge"

    systemd_networkd_network:
      "20-enp0s1":
        - Match:
            - Name: "enp0s1"
        - Network:
            - DHCP: "yes"
            - LinkLocalAddressing: "yes"
        - Link:
            - RequiredForOnline: "yes"

      "30-enp0s2":
        - Match:
            - Name: "enp0s2"
        - Network:
            - DHCP: "yes"
            - LinkLocalAddressing: "yes"
        - DHCP:
            - UseGateway: "no"
        - Link:
            - RequiredForOnline: "no"

      "40-enp0s3":
        - Match:
            - Name: "enp0s3"
        - Network:
            - Bridge: "br-mesh"
            - LinkLocalAddressing: "yes"
        - Link:
            - RequiredForOnline: "no"

      "50-br-mesh":
        - Match:
            - Name: "br-mesh"
        - Network:
            - Address: "10.10.2.1/24"
            - LinkLocalAddressing: "yes"
        - Link:
            - RequiredForOnline: "no"

  roles:
    - { role: stackhpc.linux.systemd_networkd, tags: systemd_networkd }

- name: Install packages
  hosts: "{{ target_hosts | default('node2') }}"
  become: true
  gather_facts: false
  vars:
    # idiv_biodiversity.systemd.systemd_resolved
    systemd_resolved_servers: ["172.16.300.1"]
    systemd_resolved_dnssec: false
    systemd_resolved_dns_over_tls: false
    systemd_resolved_multicast_dns: false
    systemd_resolved_llmnr: false
    systemd_resolved_cache: false
    systemd_resolved_cache_from_localhost: false
    systemd_resolved_dns_stub_listener: false
    systemd_resolved_dns_stub_listener_extra: ''
    systemd_resolved_read_etc_hosts: false
    systemd_resolved_resolve_unicast_single_label: false
    systemd_resolved_stale_retention_sec: 0

  roles:
    - { role: tools_install, tags: tools_install }
    - { role: idiv_biodiversity.systemd.systemd_resolved, tags: systemd_resolved }
    - { role: bird_install, tags: bird_install }
    - { role: bird_configure, tags: bird_configure }
    - { role: dnsmasq_install, tags: dnsmasq_install }
    - { role: dnsmasq_configure, tags: dnsmasq_configure }
