---
- name: Set up context as unprivileged user
  hosts: "{{ target_hosts | default('node2') }}"
  become: false
  gather_facts: true

- name: Install services
  hosts: "{{ target_hosts | default('node2') }}"
  become: true
  gather_facts: false
  vars:
    irc_domain: "irc2.mesh"
    irc_network_password: ""

    thelounge_name: "thelounge-neighbor"
    thelounge_port: "11002"

    ngircd_name: "ngircd-neighbor"
    ngircd_tls_port: "11004"

  roles:
    - { role: ngircd_install, tags: ngircd_install }
    - { role: thelounge_install, tags: thelounge_install }
    - { role: thelounge_themes, tags: thelounge_themes }
...
