---
- name: Set up context as unprivileged user
  hosts: "{{ target_hosts | default('local-vm') }}"
  become: false
  gather_facts: true

- name: Create temporary HTTP vhost
  hosts: "{{ target_hosts | default('local-vm') }}"
  become: true
  gather_facts: false
  vars:
    nginx_vhosts:
      - listen: "80 default_server"
        server_name: "_"
        root: "/var/www/{{ webroot_domain }}"
        filename: "nginx.test"
        state: "present"
  roles:
    - { role: webroot_create, tags: webroot_create }
    - { role: geerlingguy.nginx, tags: nginx_temp_vhost }

- name: Set up TLS certificates
  hosts: "{{ target_hosts | default('local-vm') }}"
  become: true
  gather_facts: false
  vars:
    certbot_certs:
      - name: "{{ webroot_domain }}"
        email: "{{ certbot_admin_email }}"
        webroot: "/var/www/{{ webroot_domain }}"
        domains:
          - "{{ webroot_domain }}"
          - "www.{{ webroot_domain }}"
  roles:
    - { role: geerlingguy.certbot, tags: certbot_install }

- name: Configure nginx
  hosts: "{{ target_hosts | default('local-vm') }}"
  become: true
  gather_facts: false
  vars:
    nginx_vhosts:
      - listen: "80 default_server"
        server_name: "_"
        root: "/var/www/{{ webroot_domain }}"
        filename: "nginx.test"
        state: "absent"

      - listen: "80"
        server_name: "{{ webroot_domain }} www.{{ webroot_domain }}"
        filename: "{{ webroot_domain }}.redirect.conf"
        return: "301 https://{{ webroot_domain }}$request_uri"

      - listen: "443 ssl http2"
        server_name: "{{ webroot_domain }}"
        root: "/var/www/{{ webroot_domain }}"
        filename: "{{ webroot_domain }}.conf"
        extra_parameters: |
          ssl_certificate     /etc/letsencrypt/live/{{ webroot_domain }}/fullchain.pem;
          ssl_certificate_key /etc/letsencrypt/live/{{ webroot_domain }}/privkey.pem;
  roles:
    - { role: geerlingguy.nginx, tags: nginx_tls }
...
