---
- name: Ensure transmission directories
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/{{ service.name }}/config"
    state: directory
    owner: "{{ ansible_user }}"
    mode: "0700"

- name: Copy settings.json
  ansible.builtin.copy:
    src: "transmission.settings.json/{{ service.name }}"
    dest: "{{ ansible_facts['user_dir'] }}/{{ service.name }}/config/settings.json"
    owner: "{{ ansible_user }}"
    mode: "0600"
    force: true

- name: Template compose file
  ansible.builtin.template:
    src: transmission.compose.yaml.j2
    dest: "{{ ansible_facts['user_dir'] }}/{{ service.name }}/compose.yaml"
    owner: "{{ ansible_user }}"
    mode: "0600"
    force: true
...
