---
- name: Run Ubuntu pre tasks
  ansible.builtin.import_tasks: ubuntu_pre.yaml
  when: ansible_facts["distribution"] == "Ubuntu"

- name: Run common tasks
  ansible.builtin.import_tasks: common.yaml

- name: Run Ubuntu post tasks
  ansible.builtin.import_tasks: ubuntu_post.yaml
  when: ansible_facts["distribution"] == "Ubuntu"
...
