---
- name: Add users to groups
  ansible.builtin.uri:
    url: "http://localhost:{{ control.port }}/group/{{ item.group }}/member/{{ item.name }}"
    method: PUT
    headers:
      X-API-Key: "{{ control.token }}"
  register: result
  changed_when: result.status == 200
  failed_when: false
  loop: "{{ lldap.users }}"
  loop_control:
    label: "{{ item.name }}"
...
