---
# Used only for Debian/Ubuntu installation, as the -t option for apt.
nginx_default_release: ""

# Used only for Redhat installation, enables source Nginx repo.
nginx_yum_repo_enabled: true

# Used only for Suse installation, enables source Nginx repo.
nginx_zypper_repo_enabled: true

# Use the official Nginx PPA for Ubuntu, and the version to use if so.
nginx_ppa_use: false
nginx_ppa_version: stable

# The name of the nginx package to install.
nginx_package_name: "nginx"

nginx_service_state: started
nginx_service_enabled: true

nginx_conf_template: "nginx.conf.j2"
nginx_vhost_template: "vhost.j2"

nginx_worker_processes: "{{ ansible_facts['processor_vcpus'] | default(ansible_facts['processor_count']) }}"
nginx_worker_connections: "1024"
nginx_multi_accept: "off"

nginx_error_log: "syslog:server=unix:/dev/log warn"
nginx_access_log: "syslog:server=unix:/dev/log main"

nginx_sendfile: "on"
nginx_tcp_nopush: "on"
nginx_tcp_nodelay: "on"

nginx_keepalive_timeout: "75"
nginx_keepalive_requests: "600"

nginx_server_tokens: "on"

nginx_client_max_body_size: "64m"

nginx_server_names_hash_bucket_size: "64"

nginx_proxy_cache_path: ""

nginx_extra_conf_options: ""
# Example extra main options, used within the main nginx's context:
#   nginx_extra_conf_options: |
#     env VARIABLE;
#     include /etc/nginx/main.d/*.conf;

nginx_extra_http_options: |
  ssl_protocols TLSv1.3;
  ssl_ecdh_curve X25519:prime256v1:secp384r1;
  ssl_prefer_server_ciphers off;
# Example extra http options, printed inside the main server http config:
#    nginx_extra_http_options: |
#      proxy_buffering    off;
#      proxy_set_header   X-Real-IP $remote_addr;
#      proxy_set_header   X-Scheme $scheme;
#      proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
#      proxy_set_header   Host $http_host;

nginx_remove_default_vhost: true

# Listen on IPv6 (default: true)
nginx_listen_ipv6: false

nginx_vhosts:
  # - listen: "80 default_server"
  #   server_name: "_"
  #   root: "/var/www/site.local"
  #   filename: "nginx.test"
  #   state: "absent"

  - listen: "80 default_server"
    server_name: "_"
    filename: "https.redirect.conf"
    return: "301 https://$host$request_uri"

  - listen: "443 ssl http2 default_server"
    server_name: "site.local"
    root: "/var/www/site.local"
    filename: "site.local.conf"
    extra_parameters: |
      ssl_certificate     /etc/letsencrypt/live/site.local/fullchain.pem;
      ssl_certificate_key /etc/letsencrypt/live/site.local/privkey.pem;


nginx_upstreams: []
# - name: myapp1
#   strategy: "ip_hash" # "least_conn", etc.
#   keepalive: 16 # optional
#   servers:
#     - "srv1.example.com"
#     - "srv2.example.com weight=3"
#     - "srv3.example.com"

nginx_log_format: |-
  '$remote_addr - $remote_user [$time_local] "$request" '
  '$status $body_bytes_sent "$http_referer" '
  '"$http_user_agent" "$http_x_forwarded_for"'
...
