---
all:
  hosts:
    local-vm:
      ansible_host: "192.168.64.17"

    laptop:
      ansible_host: localhost
      ansible_connection: local
      ansible_user: user
      ansible_python_interpreter: /home/user/.ansible/python/.venv/bin/python
      docker_run_as:
        user: "501"
        group: "20"
...
