---
- name: Install dnsmasq
  ansible.builtin.apt:
    state: present
    update_cache: true
    cache_valid_time: 3600
    name:
      - dnsmasq
      - dnsmasq-utils

- name: Enable and unmask dnsmasq
  ansible.builtin.systemd_service:
    name: dnsmasq.service
    state: started
    enabled: true
    masked: false
    daemon_reload: true
...
