---
- name: Ensure filebrowser directories
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/{{ filebrowser_name }}/{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    mode: "0700"
  loop:
    - config
    - branding

- name: Template filebrowser compose file
  ansible.builtin.template:
    src: filebrowser.compose.yaml.j2
    dest: "{{ ansible_facts['user_dir'] }}/{{ filebrowser_name }}/compose.yaml"
    owner: "{{ ansible_user }}"
    mode: "0600"
    force: true

- name: Template filebrowser mnt compose file
  ansible.builtin.template:
    src: filebrowser.mnt.compose.yaml.j2
    dest: "{{ ansible_facts['user_dir'] }}/{{ filebrowser_name }}/compose-mnt.yaml"
    owner: "{{ ansible_user }}"
    mode: "0600"
    force: true

- name: Copy settings json
  ansible.builtin.copy:
    src: "{{ filebrowser_name }}/{{ ansible_facts['hostname'] }}"
    dest: "{{ ansible_facts['user_dir'] }}/{{ filebrowser_name }}/config/settings.json"
    owner: "{{ ansible_user }}"
    mode: "0600"
    force: true

- name: Copy db settings json
  ansible.builtin.copy:
    src: "{{ filebrowser_name }}-db-settings/{{ ansible_facts['hostname'] }}"
    dest: "{{ ansible_facts['user_dir'] }}/{{ filebrowser_name }}/config/db.settings.json"
    owner: "{{ ansible_user }}"
    mode: "0600"
    force: true

- name: Copy branding
  ansible.builtin.copy:
    src: "filebrowser.branding/"
    dest: "{{ ansible_facts['user_dir'] }}/{{ filebrowser_name }}/branding/"
    owner: "{{ ansible_user }}"
    mode: preserve
    force: true
...
