---
ansible_user: ubuntu
ansible_port: "2200"

# linux-system-roles.journald
journald_persistent: true
journald_max_disk_size: "2048"
journald_per_user: true
journald_sync_interval: 1
journald_keep_free: "10240"

# devsec.hardening.ssh_hardening
ssh_server_ports: ["2200"]
ssh_permit_tunnel: "yes"
ssh_allow_tcp_forwarding: "yes"
sftp_enabled: true

# devsec.hardening.os_hardening
sysctl_overwrite:
  net.ipv4.ip_forward: 1

# ngircd_install
# https://hub.docker.com/r/linuxserver/ngircd/tags
ngircd_image: "linuxserver/ngircd:version-27-r1"
ngircd_port: "6667"
ngircd_tls_port: "6697"

# thelounge_install
# https://hub.docker.com/r/linuxserver/thelounge/tags
thelounge_image: "linuxserver/thelounge:4.4.3"
thelounge_port: "9000"

# ngircd_install, thelounge_install, filebrowser_install, tta_control_install, tta_telegram_bot_install
docker_cli: /usr/bin/docker

# filebrowser_install
# https://hub.docker.com/r/filebrowser/filebrowser/tags
filebrowser_image: "filebrowser/filebrowser:v2.63.2"
filebrowser_port: "10000"
filebrowser_volume_size: "100M"
filebrowser_misc_volume_size: "100M"

# tta_control_install
# https://hub.docker.com/r/nett/tta-control/tags
tta_control_image: "nett/tta-control:0.2.2"
tta_control_port: "8001"

# tta_telegram_bot_install
# https://hub.docker.com/r/nett/tta-telegram-bot/tags
tta_telegram_bot_image: "nett/tta-telegram-bot:0.2.2"
tta_telegram_bot_port: "8002"
...
