---
- name: Ensure mediawiki directories
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/{{ service.name }}/www/{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    mode: "0755"
  loop:
    - data
    - images

- name: Fix mediawiki directory permissions
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/{{ service.name }}/www/images"
    state: directory
    owner: "{{ ansible_user }}"
    mode: "0755"
    recurse: true

- name: Copy localsettings.php
  ansible.builtin.copy:
    src: "mediawiki.localsettings.php/{{ service.name }}"
    dest: "{{ ansible_facts['user_dir'] }}/{{ service.name }}/www/LocalSettings.php"
    owner: "{{ ansible_user }}"
    mode: "0600"
    force: true

- name: Template compose file
  ansible.builtin.template:
    src: mediawiki.compose.yaml.j2
    dest: "{{ ansible_facts['user_dir'] }}/{{ service.name }}/compose.yaml"
    owner: "{{ ansible_user }}"
    mode: "0600"
    force: true
...
