---
- name: Remove ufw and iptables
  ansible.builtin.apt:
    state: absent
    name:
      - ufw
      - iptables-persistent

- name: Install nftables
  ansible.builtin.apt:
    state: present
    update_cache: true
    cache_valid_time: 3600
    name:
      - nftables
      - libnftnl11

- name: Enable and unmask nftables
  ansible.builtin.systemd:
    name: nftables.service
    state: started
    enabled: true
    masked: false
...
