---
- name: Install dependencies
  ansible.builtin.apt:
    state: present
    update_cache: true
    cache_valid_time: 3600
    name:
      - coreutils
      - findutils
      - curl
      - gawk
      - grep
      - sed

- name: Download Ollama installer
  ansible.builtin.get_url:
    url: https://ollama.com/install.sh
    dest: "{{ ansible_facts['user_dir'] }}/install_ollama.sh"
    mode: '0755'

- name: Run Ollama installer
  ansible.builtin.shell: "{{ ansible_facts['user_dir'] }}/install_ollama.sh"
  args:
    executable: /usr/bin/sh
  register: install_ollama_result
  changed_when: "'Install complete.' in install_ollama_result.stdout"

- name: Enable and unmask Ollama
  ansible.builtin.systemd:
    name: ollama.service
    state: started
    enabled: true
    masked: false

- name: Add the user 'ubuntu' to 'ollama' group
  ansible.builtin.user:
    name: ubuntu
    groups: ollama
    append: true
...
