#!/usr/bin/bash

{% if transmission is defined %}
sudo systemctl stop {{ transmission.name }}
{% endif %}

{% if sftpgo is defined %}
sudo systemctl stop {{ sftpgo.name }}
docker volume rm "{{ sftpgo.name }}_{{ sftpgo.name }}-data"
docker volume prune --force
{% endif %}
