#!/usr/bin/bash

curl https://{{ tta_control_domain }}/create_filebrowser_complete_users_json -H "Content-Type: application/json" -d '{"token": "{{ tta_control_token }}"}'

{% if filebrowser_name is defined %}
mv {{ ansible_facts['user_dir'] }}/{{ tta_control_name }}/{{ tta_control_files_user_dir }}/users.json {{ ansible_facts['user_dir'] }}/{{ filebrowser_name }}/config/
sudo systemctl start {{ filebrowser_name }}
sudo systemctl start {{ filebrowser_name }}-mnt
{% endif %}

{% if transmission_name is defined %}
sudo systemctl start {{ transmission_name }}
{% endif %}
