#!/usr/bin/bash

sudo timedatectl set-ntp no
sudo timedatectl set-time "{{ now(utc=true,fmt='%Y-%m-%d %H:%M:%S') }}"

{% if ngircd_name is defined %}
sudo systemctl restart {{ ngircd_name }}
{% endif %}

{% if thelounge_name is defined %}
sudo systemctl restart {{ thelounge_name }}
{% endif %}

sudo systemctl restart {{ tta_control_name }}
