#!/usr/bin/bash

sudo timedatectl set-ntp no
sudo timedatectl set-time "{{ now(utc=true,fmt='%Y-%m-%d %H:%M:%S') }}"

{% if ngircd is defined %}
sudo systemctl restart {{ ngircd.name }}
{% endif %}

{% if thelounge is defined %}
sudo systemctl restart {{ thelounge.name }}
{% endif %}

sudo systemctl restart {{ control.name }}
