---
- name: Uninstall unofficial packages
  ansible.builtin.apt:
    state: absent
    name:
      - docker.io
      - docker-compose
      - docker-compose-v2
      - docker-doc
      - podman-docker
      - containerd
      - runc

- name: Install ca-certificates curl
  ansible.builtin.apt:
    state: present
    update_cache: true
    cache_valid_time: 3600
    name:
      - ca-certificates
      - curl

- name: Ensure apt keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Download docker apt public key
  ansible.builtin.get_url:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    dest: /etc/apt/keyrings/docker.asc
    mode: "0644"
    owner: root
    group: root
    validate_certs: true
    decompress: false
    force: false
    backup: false

- name: Remove old configuration
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/docker.list
    state: absent

- name: Add docker apt repository
  ansible.builtin.deb822_repository:
    name: docker
    types: deb
    uris: https://download.docker.com/linux/ubuntu
    suites: "{{ ansible_facts['distribution_release'] }}"
    components: stable
    signed_by: /etc/apt/keyrings/docker.asc
    state: present
    enabled: true
    mode: "0644"
    by_hash: true
    check_date: true
    check_valid_until: true
    pdiffs: true
    allow_insecure: false
    allow_weak: false
    install_python_debian: true

- name: Install docker
  ansible.builtin.apt:
    state: present
    update_cache: true
    cache_valid_time: 3600
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

- name: Enable and unmask docker
  ansible.builtin.systemd_service:
    name: docker.service
    state: started
    enabled: true
    masked: false
    daemon_reload: true

- name: Ensure docker group exists
  ansible.builtin.group:
    name: docker
    state: present
    system: true
    force: false

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
    state: present
    force: false
...
