---
- name: Template sftpgo systemd service
  ansible.builtin.template:
    src: sftpgo.service.j2
    dest: /etc/systemd/system/{{ sftpgo_name }}.service
    owner: root
    group: root
    mode: "0644"
    force: true

- name: Start sftpgo
  ansible.builtin.systemd_service:
    name: "{{ sftpgo_name }}.service"
    state: restarted
    enabled: true
    masked: false
    daemon_reload: true
...
