---
- name: Replace users dir
  ansible.posix.synchronize:
    src: thelounge.users/
    dest: "{{ ansible_facts['user_dir'] }}/thelounge/config/users"
    archive: true
    recursive: true
    delete: true
    mode: "push"
    rsync_opts:
      - "--include=*.json"
      - "--exclude=*"

- name: Update file ownership
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/thelounge/config/users"
    owner: "{{ ansible_user }}"
    state: directory
    recurse: true

- name: Update directory permissions
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/thelounge/config/users"
    owner: "{{ ansible_user }}"
    state: directory
    mode: "0700"
...
