---
- name: Ensure thelounge_telegram_accounts directories
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/thelounge_telegram_accounts/data"
    state: directory
    owner: "{{ ansible_user }}"
    mode: "0700"

- name: Copy env file
  ansible.builtin.copy:
    src: "thelounge.telegram.accounts.env/{{ ansible_facts['hostname'] }}"
    dest: "{{ ansible_facts['user_dir'] }}/thelounge_telegram_accounts/bot.env"
    owner: "{{ ansible_user }}"
    mode: "0600"
    force: true

- name: Template compose file
  ansible.builtin.template:
    src: thelounge.telegram.accounts.compose.yaml.j2
    dest: "{{ ansible_facts['user_dir'] }}/thelounge_telegram_accounts/compose.yaml"
    owner: "{{ ansible_user }}"
    mode: "0600"
    force: true
...
