---
- name: Install tools
  ansible.builtin.apt:
    state: present
    update_cache: true
    cache_valid_time: 3600
    name:
      - bind9-dnsutils
      - bridge-utils
      - curl
      - dnsmasq-utils
      - git
      - iftop
      - inetutils-traceroute
      - iproute2
      - irssi
      - isc-dhcp-client
      - ldap-utils
      - net-tools
      - sqlite3
      - tcpdump
      - vim
...
