---
- name: Create directories
  ansible.builtin.file:
    path: "/var/www/{{ item }}"
    state: directory
    owner: www-data
    group: www-data
    mode: "0770"
  loop: "{{ webroot_domain }}"

- name: Copy stub page
  ansible.builtin.copy:
    src: "webroot.index.html"
    dest: "/var/www/{{ item }}/index.html"
    owner: www-data
    group: www-data
    mode: "0640"
    force: true
  loop: "{{ webroot_domain }}"
...
