---
- name: Create directories
  ansible.builtin.file:
    path: "/var/www/{{ webroot_domain }}"
    state: directory
    owner: www-data
    group: www-data
    mode: "0775"

- name: Copy stub page
  ansible.builtin.copy:
    src: "webroot.index.html"
    dest: "/var/www/{{ webroot_domain }}/index.html"
    owner: www-data
    group: www-data
    mode: "0644"
    force: true

- name: Add ansible_user to the www-data group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: www-data
    append: true
    state: present
...
