---
- name: Create directories
  ansible.builtin.file:
    path: "/var/www/health"
    state: directory
    owner: www-data
    group: www-data
    mode: "0775"

- name: Copy stub page
  ansible.builtin.copy:
    src: "health.index.html"
    dest: "/var/www/health/index.html"
    owner: www-data
    group: www-data
    mode: "0644"
    force: true

- name: Add ansible_user to the www-data, systemd-journal groups
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: www-data,systemd-journal
    append: true
    state: present

- name: Copy health check script
  ansible.builtin.copy:
    src: "health_check.sh"
    dest: "{{ ansible_facts['user_dir'] }}/health_check.sh"
    owner: "{{ ansible_user }}"
    mode: "0750"
    force: true

- name: Schedule health check
  ansible.builtin.cron:
    user: "{{ ansible_user }}"
    name: "Health check"
    minute: "*"
    hour: "*"
    day: "*"
    month: "*"
    weekday: "*"
    job: "{{ ansible_facts['user_dir'] }}/health_check.sh /var/www/health/index.html"
...
