---
- name: Populate service facts
  ansible.builtin.service_facts:

- name: Copy nftables.conf
  ansible.builtin.copy:
    src: "nftables.conf/{{ ansible_facts['hostname'] }}"
    dest: /etc/nftables.conf
    owner: root
    group: root
    mode: "0644"
    force: true
    validate: nft --check -f %s
  notify:
    - NftablesRestart
    - DockerRestartIfRunning
...
